### ISSUE TITLE
flashocc环境安装和文件路径错误问题

### ISSUE THREAD

**Issue by xioatian1** [Yzichen/FlashOCC#1]
感谢你们开源了这个优秀的项目！
但我在复现代码的时候遇到了问题，我看到该工作是基于BEVdet是实现的，于是我尝试用我之前的BEVDet的环境去实现你们的项目。可是出现了如图所示的问题：（我的环境跑BEVDet是没有问题的）
![image](https://github.com/Yzichen/FlashOCC/assets/129817358/f9101cb3-d769-4a2d-8986-229f9973c622)
他的文件路径出现了问题，我尝试修改相关路径都失败了，您能给我提供一下解决方案或者建议吗？谢谢！

**Comment by Yzichen** [comment]
https://github.com/Yzichen/FlashOCC/blob/845a6a83abee73d830316763ea5f44be5f162499/projects/mmdet3d_plugin/datasets/nuscenes_dataset_occ.py#L59

If you didn't use my create_data script, you need to modify it to:
input_dict['occ_gt_path'] = self.data_infos[index]['occ_path']

**Comment by xioatian1** [comment]
非常感谢您的回复！
我刚才按照您的建议，修改相关代码并去对比生成pkl文件的代码，发现和我之前版本的文件有一定差别，我重新生成pkl文件，代码没有问题能顺利运行了。我将会关闭这个issue
Thank you very much for your reply! 
I just followed your suggestion, modified the relevant code and compared it with the code that generates the pkl file. I found that there is some difference from the previous version of the file. I regenerated the pkl file and the code can run smoothly without any problem.
