### ISSUE TITLE
TensorRT Implement Writen In C++ With Cuda Acceleration

### ISSUE THREAD

**Issue by linClubs** [Yzichen/FlashOCC#10]
Thank you very much for your awesome work. When will support it TensorRT(C++) Implement?

**Comment by drilistbox** [comment]
The code has been integrated 2 week ago, but the results from the C++ version do not align with the results from the Torch version. 

Due to time limitatiion, it is expected to take about 2-3 weeks to align them.

**Comment by linClubs** [comment]
thanks

**Comment by drilistbox** [comment]
Hi, we release the TensorRT(C++) Implement at https://github.com/drilistbox/TRT_FlashOcc

**Comment by linClubs** [comment]
> Hi, we release the TensorRT(C++) Implement at https://github.com/drilistbox/TRT_FlashOcc

感谢

**Comment by linClubs** [comment]
> Hi, we release the TensorRT(C++) Implement at https://github.com/drilistbox/TRT_FlashOcc

Thank you very much for your awesome work. Does it support Occ with TensorRT(C++) Implement？

**Comment by drilistbox** [comment]
Yes

**Comment by 1ManekiNeko** [comment]
感谢大佬们的开源工作，谢谢。
佬们之前那个TensorRT(C++) Implement没了，我用的 https://github.com/hitumwangli/TRT_FlashOcc
试着跑了demo，3.3步的精度验证，发现精度达不到"acc is: 0.998534375"，差得非常多啊 ...

**Comment by upupbo** [comment]
> Hi, we release the TensorRT(C++) Implement at https://github.com/drilistbox/TRT_FlashOcc
This link is broken

**Comment by Samsara011** [comment]
@linClubs @Yzichen Hello, can the project still open? The link is invalid! Looking forward to your reply
