### ISSUE TITLE
The link is broken 

### ISSUE THREAD

**Issue by MingkangXiong** [Yzichen/FlashOCC#11]
The link of the model for BEVDetOCC-R50 is broken.

**Comment by drilistbox** [comment]
I try and find it ok.
flashocc-r50-256x704.pth: https://drive.google.com/file/d/14my3jdqiIv6VIrkozQ6-ruEcBOPVlWGJ/view
flashocc-r50-M0-256x704.pth: https://drive.google.com/file/d/14my3jdqiIv6VIrkozQ6-ruEcBOPVlWGJ/view

**Comment by drilistbox** [comment]
upload at https://pan.baidu.com/share/init?surl=2XWqv4jpOsidlhopStU9xA&pwd=xcr9
