### ISSUE TITLE
FlashOcc on UniOCC and FB-OCC

### ISSUE THREAD

**Issue by Kongbaikb** [Yzichen/FlashOCC#12]
Thank you for your outstanding work! May I ask when your FlashOcc on UniOCC and FB-OCC code will be open source?

**Comment by drilistbox** [comment]
2 weeks

**Comment by drilistbox** [comment]
We release the code and model for FO(UniOcc) at https://github.com/drilistbox/FlashOCC_on_UniOcc_and_RenderOCC.
