### ISSUE TITLE
May I ask the center of Occ3D dataset ground truth coordinate

### ISSUE THREAD

**Issue by DanielMing123** [Yzichen/FlashOCC#13]
In the environment setup process in step 4 for the occupancy prediction task, the guideline told us to only download gts from the occ3d dataset. May I ask which coordinate the occ3d dataset uses? Does the occ3d dataset use Nuscenes ego coordinates as their ground truth centre?

**Comment by Yzichen** [comment]
I think it uses the ego coordinate system.

**Comment by DanielMing123** [comment]
ok, thanks for the reply, I will give it a try.
