### ISSUE TITLE
Onnx model

### ISSUE THREAD

**Issue by CrazyMustard-404** [Yzichen/FlashOCC#15]
Hi, thank you for your outstanding work. Could you please advise on how to convert the model weights to ONNX format, or provide the ONNX file if possible?

**Comment by drilistbox** [comment]
Run tools/convert_bevdet_to_TRT.py follow https://github.com/Yzichen/FlashOCC/blob/master/doc/mmdeploy_test.md to get onnx.

**Comment by CrazyMustard-404** [comment]
> Run tools/convert_bevdet_to_TRT.py follow https://github.com/Yzichen/FlashOCC/blob/master/doc/mmdeploy_test.md to get onnx.

Thank you very much for your response! When I tried to run it following the method you provided, I encountered the following error. I'm not sure where the problem lies. Could you offer me some advice?

(OCC) 3@1:~/FlashOCC-master$ exp_name=flashocc-r50-M0
(OCC) 3@1:~/FlashOCC-master$ fold_name=flashocc
(OCC) 3@1:~/FlashOCC-master$ config=projects/configs/flashocc/flashocc-r50-M0-trt.py
(OCC) 3@1:~/FlashOCC-master$ checkpoint=ckpts/flashocc-r50-M0-256x704.pth
(OCC) 3@1:~/FlashOCC-master$ work_dir=work_dirs/flashocc_r50_M0/onnx_trt/
(OCC) 3@1:~/FlashOCC-master$ 
(OCC) 3@1:~/FlashOCC-master$ 
(OCC) 3@1:~/FlashOCC-master$ engine=work_dirs/flashocc-r50-M0-256x704/onnx_trt/bevdet_int8_fuse.engine
(OCC) 3@1:~/FlashOCC-master$ 
(OCC) 3@1:~/FlashOCC-master$ CUDA_VISIBLE_DEVICES=0 python tools/convert_bevdet_to_TRT.py projects/configs/flashocc/flashocc-r50-M0-trt.py ckpts/flashocc-r50-M0-256x704.pth work_dirs/flashocc_r50_M0 --fuse-conv-bn --fp16 --int8 --calib_num 32
Traceback (most recent call last):
  File "tools/convert_bevdet_to_TRT.py", line 8, in <module>
    from mmdeploy.backend.tensorrt.utils import save, search_cuda_version
  File "/home/xinjishu-workstation3/anaconda3/envs/OCC/lib/python3.8/site-packages/mmdeploy/__init__.py", line 8, in <module>
    importlib.import_module('mmdeploy.pytorch')
  File "/home/xinjishu-workstation3/anaconda3/envs/OCC/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/xinjishu-workstation3/anaconda3/envs/OCC/lib/python3.8/site-packages/mmdeploy/pytorch/__init__.py", line 2, in <module>
    from . import functions  # noqa: F401,F403
  File "/home/xinjishu-workstation3/anaconda3/envs/OCC/lib/python3.8/site-packages/mmdeploy/pytorch/functions/__init__.py", line 2, in <module>
    from . import adaptive_pool  # noqa: F401,F403
  File "/home/xinjishu-workstation3/anaconda3/envs/OCC/lib/python3.8/site-packages/mmdeploy/pytorch/functions/adaptive_pool.py", line 6, in <module>
    from mmdeploy.core import FUNCTION_REWRITER
  File "/home/xinjishu-workstation3/anaconda3/envs/OCC/lib/python3.8/site-packages/mmdeploy/core/__init__.py", line 2, in <module>
    from .optimizers import *  # noqa: F401,F403
  File "/home/xinjishu-workstation3/anaconda3/envs/OCC/lib/python3.8/site-packages/mmdeploy/core/optimizers/__init__.py", line 2, in <module>
    from .extractor import create_extractor, parse_extractor_io_string
  File "/home/xinjishu-workstation3/anaconda3/envs/OCC/lib/python3.8/site-packages/mmdeploy/core/optimizers/extractor.py", line 4, in <module>
    import onnx
  File "/home/xinjishu-workstation3/FY/FlashOCC-master/onnx.py", line 10, in <module>
    from mmdeploy.backend.tensorrt.utils import save, search_cuda_version
  File "/home/xinjishu-workstation3/anaconda3/envs/OCC/lib/python3.8/site-packages/mmdeploy/backend/tensorrt/__init__.py", line 13, in <module>
    from .utils import from_onnx, load, save
  File "/home/xinjishu-workstation3/anaconda3/envs/OCC/lib/python3.8/site-packages/mmdeploy/backend/tensorrt/utils.py", line 98, in <module>
    def from_onnx(onnx_model: Union[str, onnx.ModelProto],
AttributeError: partially initialized module 'onnx' has no attribute 'ModelProto' (most likely due to a circular import)

**Comment by CrazyMustard-404** [comment]
> Run tools/convert_bevdet_to_TRT.py follow https://github.com/Yzichen/FlashOCC/blob/master/doc/mmdeploy_test.md to get onnx.

Thank you very much for your response! When I tried to run it following the method you provided, I encountered the following error. I'm not sure where the problem lies. Could you offer me some advice?

(OCC) 3@1:/FlashOCC-master$ exp_name=flashocc-r50-M0
(OCC) 3@1:/FlashOCC-master$ fold_name=flashocc
(OCC) 3@1:/FlashOCC-master$ config=projects/configs/flashocc/flashocc-r50-M0-trt.py
(OCC) 3@1:/FlashOCC-master$ checkpoint=ckpts/flashocc-r50-M0-256x704.pth
(OCC) 3@1:/FlashOCC-master$ work_dir=work_dirs/flashocc_r50_M0/onnx_trt/
(OCC) 3@1:/FlashOCC-master$
(OCC) 3@1:/FlashOCC-master$
(OCC) 3@1:/FlashOCC-master$ engine=work_dirs/flashocc-r50-M0-256x704/onnx_trt/bevdet_int8_fuse.engine
(OCC) 3@1:/FlashOCC-master$
(OCC) 3@1:/FlashOCC-master$ CUDA_VISIBLE_DEVICES=0 python tools/convert_bevdet_to_TRT.py projects/configs/flashocc/flashocc-r50-M0-trt.py ckpts/flashocc-r50-M0-256x704.pth work_dirs/flashocc_r50_M0 --fuse-conv-bn --fp16 --int8 --calib_num 32

02/19 15:06:50 - mmengine - INFO - Successfully loaded tensorrt plugins from /home/xinjishu-workstation3/anaconda3/envs/OCC/lib/python3.8/site-packages/mmdeploy/lib/libmmdeploy_tensorrt_ops.so
Traceback (most recent call last):
  File "tools/convert_bevdet_to_TRT.py", line 546, in <module>
    main()
  File "tools/convert_bevdet_to_TRT.py", line 311, in main
    assert 'bev_pool_v2' in get_plugin_names(), \
AssertionError: bev_pool_v2 is not in the plugin list of tensorrt, please install mmdeploy from https://github.com/HuangJunJie2017/mmdeploy.git


(Requirement already satisfied: mmdeploy in /home/xinjishu-workstation3/anaconda3/envs/OCC/lib/python3.8/site-packages (1.3.1))

**Comment by drilistbox** [comment]
You need to install env follow https://github.com/Yzichen/FlashOCC/blob/master/doc/install.md until step 6.

**Comment by CrazyMustard-404** [comment]
> You need to install env follow https://github.com/Yzichen/FlashOCC/blob/master/doc/install.md until step 6.


Thank you very much for your response and assistance! Following your advice, I installed TensorRT and some libraries, and I was able to generate the ONNX file successfully. However, I still encountered some issues while converting to TRT format. Could it be that there's a problem with my command execution? I appreciate your help once again.

(OCC) 3@1:/FlashOCC-master$ exp_name=flashocc-r50-M0
(OCC) 3@1:/FlashOCC-master$ fold_name=flashocc
(OCC) 3@1:/FlashOCC-master$ config=projects/configs/flashocc/flashocc-r50-M0-trt.py
(OCC) 3@1:/FlashOCC-master$ checkpoint=ckpts/flashocc-r50-M0-256x704.pth
(OCC) 3@1:/FlashOCC-master$ work_dir=work_dirs/flashocc_r50_M0/onnx_trt/
(OCC) 3@1:/FlashOCC-master$
(OCC) 3@1:/FlashOCC-master$
(OCC) 3@1:/FlashOCC-master$ engine=work_dirs/flashocc-r50-M0-256x704/onnx_trt/bevdet_int8_fuse.engine
(OCC) 3@1:/FlashOCC-master$
(OCC) 3@1:/FlashOCC-master$ CUDA_VISIBLE_DEVICES=0 python tools/convert_bevdet_to_TRT.py projects/configs/flashocc/flashocc-r50-M0-trt.py ckpts/flashocc-r50-M0-256x704.pth work_dirs/flashocc_r50_M0 --fuse-conv-bn --fp16 --int8 --calib_num 32

/home/anaconda3/envs/OCC/lib/python3.8/site-packages/mmdet/models/backbones/resnet.py:401: UserWarning: DeprecationWarning: pretrained is deprecated, please use "init_cfg" instead
  warnings.warn('DeprecationWarning: pretrained is deprecated, '
/home/anaconda3/envs/OCC/lib/python3.8/site-packages/mmdet/models/losses/cross_entropy_loss.py:239: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with PyTorch official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
load checkpoint from local path: ckpts/flashocc-r50-M0-256x704.pth
/home/FlashOCC-master/projects/mmdet3d_plugin/datasets/pipelines/loading.py:361: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:210.)
  gt_boxes, gt_labels = torch.Tensor(gt_boxes), torch.tensor(gt_labels)
/home/FlashOCC-master/projects/mmdet3d_plugin/datasets/pipelines/loading.py:361: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:210.)
  gt_boxes, gt_labels = torch.Tensor(gt_boxes), torch.tensor(gt_labels)
/home/FlashOCC-master/projects/mmdet3d_plugin/datasets/pipelines/loading.py:361: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:210.)
  gt_boxes, gt_labels = torch.Tensor(gt_boxes), torch.tensor(gt_labels)
/home/FlashOCC-master/projects/mmdet3d_plugin/datasets/pipelines/loading.py:361: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:210.)
  gt_boxes, gt_labels = torch.Tensor(gt_boxes), torch.tensor(gt_labels)
/home/FlashOCC-master/projects/mmdet3d_plugin/models/necks/view_transformer.py:288: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  ranks_depth = torch.range(
/home/FlashOCC-master/projects/mmdet3d_plugin/models/necks/view_transformer.py:290: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  ranks_feat = torch.range(
/home/FlashOCC-master/projects/mmdet3d_plugin/models/necks/view_transformer.py:301: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  batch_idx = torch.range(0, B - 1).reshape(B, 1). \
/home/FlashOCC-master/projects/mmdet3d_plugin/models/detectors/bevdet_occ.py:332: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  int(self.img_view_transformer.grid_size[0].item()),
/home/FlashOCC-master/projects/mmdet3d_plugin/models/detectors/bevdet_occ.py:333: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  int(self.img_view_transformer.grid_size[1].item()),
/home/FlashOCC-master/projects/mmdet3d_plugin/models/detectors/bevdet_occ.py:334: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  int(self.img_view_transformer.grid_size[2].item())
WARNING: The shape inference of mmdeploy::bev_pool_v2 type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::bev_pool_v2 type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::bev_pool_v2 type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
output_names: ['output_0']
====== onnx is saved at :  work_dirs/flashocc_r50_M0bevdet_int8_fuse.onnx
ONNX Model Correct
WARNING: The shape inference of mmdeploy::bev_pool_v2 type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::bev_pool_v2 type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::bev_pool_v2 type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
output_names: ['cls_occ_label']
====== onnx is saved at :  work_dirs/flashocc_r50_M0bevdet_int8_fuse_with_argmax.onnx
ONNX Model Correct
  0%|                                                                                                                                                                             | 0/6019 [00:00<?, ?it/s]/home/FlashOCC-master/projects/mmdet3d_plugin/datasets/pipelines/loading.py:361: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:210.)
  gt_boxes, gt_labels = torch.Tensor(gt_boxes), torch.tensor(gt_labels)
  1%|▉                                                                                                                                                                   | 33/6019 [00:06<18:43,  5.33it/s]
2024-02-20 17:47:35,522 - mmdeploy - INFO - Successfully loaded tensorrt plugins from /home/FlashOCC-master/mmdeploy/build/lib/libmmdeploy_tensorrt_ops.so
tools/convert_bevdet_to_TRT.py:253: DeprecationWarning: Use set_memory_pool_limit instead.
  config.max_workspace_size = max_workspace_size
tools/convert_bevdet_to_TRT.py:293: DeprecationWarning: Use build_serialized_network instead.
  engine = builder.build_engine(network, config)
0/33
段错误 (核心已转储)

**Comment by drilistbox** [comment]
You have already get onnx
====== onnx is saved at : work_dirs/flashocc_r50_M0bevdet_int8_fuse.onnx
====== onnx is saved at : work_dirs/flashocc_r50_M0bevdet_int8_fuse_with_argmax.onnx

but there seem some error when generating trt engine.
