### ISSUE TITLE
Environment Setup

### ISSUE THREAD

**Issue by yanyangchun** [Yzichen/FlashOCC#17]
sudo apt-get install python3-dev 
sudo apt-get install libevent-dev
sudo apt-get groupinstall 'development tools

Hi, please tell me, when setuping the environment, do I have to install the above libraries in the environment?
These operations require sudo permissions, but on my development machine, sudo permissions require some application.

**Comment by drilistbox** [comment]
Did you meet any error if not install the package above when training the model?

**Comment by yanyangchun** [comment]
> Sorry, we forget the dependence. But did you meet any error if not install the package above when training the model?

I had a try, but I encountered the following problem:
=======================================================
/home/users/yangchun.yan/venv/FlashOCC_venv/lib/python3.8/site-packages/mmdet/utils/setup_env.py:38: UserWarning: Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
/home/users/yangchun.yan/venv/FlashOCC_venv/lib/python3.8/site-packages/mmdet/utils/setup_env.py:48: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
projects.mmdet3d_plugin
Traceback (most recent call last):
  File "tools/train.py", line 286, in <module>
    main()
  File "tools/train.py", line 139, in main
    plg_lib = importlib.import_module(_module_path)
  File "/home/users/yangchun.yan/venv/FlashOCC_venv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'projects'
==============================================
But I tried it in python3，it can be imported.
Python 3.8.12 (default, Jan 10 2024, 14:32:25)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import projects.mmdet3d_plugin
>>>

**Comment by yanyangchun** [comment]
> > Sorry, we forget the dependence. But did you meet any error if not install the package above when training the model?
> 
> I had a try, but I encountered the following problem:
> 
> /home/users/yangchun.yan/venv/FlashOCC_venv/lib/python3.8/site-packages/mmdet/utils/setup_env.py:38: UserWarning: Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. warnings.warn( /home/users/yangchun.yan/venv/FlashOCC_venv/lib/python3.8/site-packages/mmdet/utils/setup_env.py:48: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. warnings.warn( projects.mmdet3d_plugin Traceback (most recent call last): File "tools/train.py", line 286, in main() File "tools/train.py", line 139, in main plg_lib = importlib.import_module(_module_path) File "/home/users/yangchun.yan/venv/FlashOCC_venv/lib/python3.8/importlib/**init**.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1014, in _gcd_import File "", line 991, in _find_and_load File "", line 961, in _find_and_load_unlocked File "", line 219, in _call_with_frames_removed File "", line 1014, in _gcd_import File "", line 991, in _find_and_load File "", line 973, in _find_and_load_unlocked ModuleNotFoundError: No module named 'projects'
> 
> But I tried it in python3，it can be imported. Python 3.8.12 (default, Jan 10 2024, 14:32:25) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import projects.mmdet3d_plugin

when I debugged it:
import sys

**Comment by yanyangchun** [comment]
Hi, I continue to run training pipeline, but I met the following problem, I debugged it, found that BEVDetOCC is not in registry.module_dict.keys(). And registry.module_dict.keys() is not None.
===========
Traceback (most recent call last):
  File "tools/train.py", line 291, in <module>
    main()
  File "tools/train.py", line 247, in main
    model = build_model(
  File "/home/users/yangchun.yan/FlashOCC/mmdetection3d/mmdet3d/models/builder.py", line 122, in build_model
    return build_detector(cfg, train_cfg=train_cfg, test_cfg=test_cfg)
  File "/home/users/yangchun.yan/FlashOCC/mmdetection3d/mmdet3d/models/builder.py", line 95, in build_detector
    return MMDET_DETECTORS.build(
  File "/home/users/yangchun.yan/venv/FlashOCC_venv/lib/python3.8/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/users/yangchun.yan/venv/FlashOCC_venv/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/users/yangchun.yan/venv/FlashOCC_venv/lib/python3.8/site-packages/mmcv/utils/registry.py", line 61, in build_from_cfg
    raise KeyError(
KeyError: 'BEVDetOCC is not in the models registry'

**Comment by yanyangchun** [comment]
> Hi, I continue to run training pipeline, but I met the following problem, I debugged it, found that BEVDetOCC is not in registry.module_dict.keys(). And registry.module_dict.keys() is not None.
> 
> Traceback (most recent call last): File "tools/train.py", line 291, in main() File "tools/train.py", line 247, in main model = build_model( File "/home/users/yangchun.yan/FlashOCC/mmdetection3d/mmdet3d/models/builder.py", line 122, in build_model return build_detector(cfg, train_cfg=train_cfg, test_cfg=test_cfg) File "/home/users/yangchun.yan/FlashOCC/mmdetection3d/mmdet3d/models/builder.py", line 95, in build_detector return MMDET_DETECTORS.build( File "/home/users/yangchun.yan/venv/FlashOCC_venv/lib/python3.8/site-packages/mmcv/utils/registry.py", line 237, in build return self.build_func(*args, **kwargs, registry=self) File "/home/users/yangchun.yan/venv/FlashOCC_venv/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg return build_from_cfg(cfg, registry, default_args) File "/home/users/yangchun.yan/venv/FlashOCC_venv/lib/python3.8/site-packages/mmcv/utils/registry.py", line 61, in build_from_cfg raise KeyError( KeyError: 'BEVDetOCC is not in the models registry'

export PYTHONPATH=/path/to/FlashOCC:$PYTHONPATH
fixed it.

**Comment by yanyangchun** [comment]
sudo apt-get install python3-dev
sudo apt-get install libevent-dev
sudo apt-get groupinstall 'development tools
pip install pycuda 

I have not installed the above libraries, but currently I can train and infer on 3090 gpus.
