### ISSUE TITLE
KeyError: 'MEGVIIEMAHook is already registered in hook'

### ISSUE THREAD

**Issue by YeL6** [Yzichen/FlashOCC#2]
Thank you for your great work！
I encountered an issue while using both your test and training code. It appears to be related to a problem with repeat registration. Could you please give me some guidance on how to fix this issue?

![image](https://github.com/Yzichen/FlashOCC/assets/74295796/a8e02cdd-3161-4b69-b7ce-09334cabe9f7)

**Comment by YeL6** [comment]
I configured my environment according to BEVDet

The relevant configuration is as follows

> matplotlib              3.5.3
matplotlib-inline       0.1.6
mccabe                  0.7.0
mkl-fft                 1.3.8
mkl-random              1.2.4
mkl-service             2.4.0
mmcls                   0.25.0
mmcv-full               1.5.3
mmdeploy                0.9.0        /root/workspace/mmdeploy
mmdet                   2.25.1
mmdet3d                 1.0.0rc4     /root/BEVDet
mmsegmentation          0.25.0

I hope it is helpful for you to reproduce this problem

**Comment by Yzichen** [comment]
Use the original mmdetection3d or use force=True when registering.
