### ISSUE TITLE
FlashOcc on FB-OCC

### ISSUE THREAD

**Issue by lvchuandong** [Yzichen/FlashOCC#21]
May I ask when your FlashOcc on FB-OCC code will be open source? Thank you very very much.

**Comment by Terencedu** [comment]
Hi, 
Just a simple question.
FB-OCC is not open-source, how you reproduce it? Just based on the FB-OCC paper?

**Comment by hyeon-mun** [comment]
> Hi, Just a simple question. FB-OCC is not open-source, how you reproduce it? Just based on the FB-OCC paper?

code is publicly available
https://github.com/NVlabs/FB-BEV
