### ISSUE TITLE
align_after_view_transfromation

### ISSUE THREAD

**Issue by yanyangchun** [Yzichen/FlashOCC#24]
请教下，时序模型的cfgs中，我看align_after_view_transfromation这个参数被设置为false，这是为什么呢？
获得时序的bev feats后，不需要对齐到当前帧了吗？

**Comment by yanyangchun** [comment]
![image](https://github.com/Yzichen/FlashOCC/assets/48945176/c131777e-a560-4362-81e1-34ab08a33649)
同时，也想请教下，截图位置的代码，mlp_input是什么呢？（辛苦帮忙解答下）
get_mlp_input()中传入的是当前帧的外参，对于历史帧也是当前帧的外参，这点是为什么呢？

**Comment by Yzichen** [comment]
> 请教下，时序模型的cfgs中，我看align_after_view_transfromation这个参数被设置为false，这是为什么呢？ 获得时序的bev feats后，不需要对齐到当前帧了吗？

When align_after_view_transformation=True, this indicates that the temporal alignment is done in the view transformer, rather than through the warp of the bev feature map. Specifically, the temporal alignment is done by transforming the frustum points of the history frame to the current ego coordinate system as well, via sensor2keyego.

**Comment by Yzichen** [comment]
> ![image](https://private-user-images.githubusercontent.com/48945176/312298885-c131777e-a560-4362-81e1-34ab08a33649.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MTgyMzIsIm5iZiI6MTcxMDQxNzkzMiwicGF0aCI6Ii80ODk0NTE3Ni8zMTIyOTg4ODUtYzEzMTc3N2UtYTU2MC00MzYyLTgxZTEtMzRhYjA4YTMzNjQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDEyMDUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3MjYxZjVkMjYwMmI2NjUzMGQzNDJmMDQxNTUxMmJhMGNiZTAzNjQ0MjY4MzYxYjg1YTU2OWVmY2Q2Nzg5MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mu_pgNnCtflS9NK7obbzXytgjx-WD-lD-NmNJX_bQeA) 同时，也想请教下，截图位置的代码，mlp_input是什么呢？（辛苦帮忙解答下） get_mlp_input()中传入的是当前帧的外参，对于历史帧也是当前帧的外参，这点是为什么呢？

You should refer to BEVDepth, which introduces camera parameters into the depth estimation network to get a camera-aware depth estimate. And the camera parameters are the same for different frames, so it is enough to use the parameters of the current frame.
You have to note that while sensor2ego is the same for different frames, sensor2keyego is different for different frames, which represents the transformation of the camera coordinate system to the current ego coordinate system.
