### ISSUE TITLE
class weight setting in BEVOCCHead2D and BEVOCCHead2D_V2

### ISSUE THREAD

**Issue by Rayn-Wu** [Yzichen/FlashOCC#27]
Hi, in your **BEVOCCHead2D**, the class balance setting is :
```
            if self.class_balance:
                valid_voxels = voxel_semantics[mask_camera.bool()]
                num_total_samples = 0
                for i in range(self.num_classes):
                    num_total_samples += (valid_voxels == i).sum() * self.cls_weights[i]
            else:
                num_total_samples = mask_camera.sum()

            loss_occ = self.loss_occ(
                            preds,      # (B*Dx*Dy*Dz, n_cls)
                            voxel_semantics,    # (B*Dx*Dy*Dz, )
                            mask_camera,        # (B*Dx*Dy*Dz, )
                            avg_factor=num_total_samples
                        )
                        loss['loss_occ'] = loss_occ
```
However, the defined `self.cls_weights` is not used in cross entropy unlike in **BEVOCCHead2D_V2**. And I am wondering the how the class balance setting works in  **BEVOCCHead2D**.
Also,  in **BEVOCCHead2D_V2** 'camera mask' is not used, right?

**Comment by Yzichen** [comment]
When using CE loss, cls_weight also works：
https://github.com/Yzichen/FlashOCC/blob/54b0100985b3c110200a70d8cd917e88716daa78/projects/mmdet3d_plugin/models/dense_heads/bev_occ_head.py#L68-L71

Besides, the camera mask is not used in FlashoccV2.
