### ISSUE TITLE
label.npz 文件

### ISSUE THREAD

**Issue by guoningwang** [Yzichen/FlashOCC#30]
Hello author, may I ask if it is possible to train, test, and visualize our own dataset without the label.npz file. I have now achieved the conversion of my annotated dataset into nuscenes. Thank you, looking forward to your reply.

**Comment by Yzichen** [comment]
Unfortunately, it is not possible to train or inference with the current model without the occupation gt label. And how to generate occupation gt is only described in the paper (refer to https://tsinghua-mars-lab.github.io/Occ3D), but there is no open source related implementation.
