### ISSUE TITLE
About feature map

### ISSUE THREAD

**Issue by dzp17** [Yzichen/FlashOCC#31]
Hi, Thank you very much for open-sourcing your code. I have a question I'd like to ask you. I have noticed that many object detection or OCC tasks utilize 16x downsampling, followed by depth distribution estimation on the feature maps. Have you experimented with 4x or 8x feature maps? What are the constraints, such as memory and GPU?

**Comment by Yzichen** [comment]
Sorry， I have not tried using a larger feature map.
