### ISSUE TITLE
RuntimeError: Ninja is required to load C++ extensions

### ISSUE THREAD

**Issue by Jacky-gsq** [Yzichen/FlashOCC#32]
Hi, thanks for your great work!
I have followed the install.md to setup the env, but i got the following error when i train the model with config "projects/configs/flashocc/flashocc-stbase-4d-stereo-512x1408_4x4_1e-2.py". 

> Ninja is required to load C++ extensions
>   File "/FlashOCC/projects/mmdet3d_plugin/core/evaluation/ray_metrics.py", line 12, in <module>
>     dvr = load("dvr", sources=["lib/dvr/dvr.cpp", "lib/dvr/dvr.cu"], verbose=True, extra_cuda_cflags=['-allow-unsupported-compiler'])
>   File "FlashOCC/projects/mmdet3d_plugin/datasets/nuscenes_dataset_occ.py", line 13, in <module>
>     from ..core.evaluation.ray_metrics import main as calc_rayiou
>   File "/FlashOCC/projects/mmdet3d_plugin/datasets/__init__.py", line 2, in <module>
>     from .nuscenes_dataset_occ import NuScenesDatasetOccpancy
>   File "FlashOCC/projects/mmdet3d_plugin/__init__.py", line 1, in <module>
>     from .datasets import *
>   File "FlashOCC/train.py", line 139, in main
>     plg_lib = importlib.import_module(_module_path)
>   File "FlashOCC/train.py", line 286, in <module>
>     main()
> RuntimeError: Ninja is required to load C++ extensions

**Comment by Yzichen** [comment]
pip install ninja 
sudo apt-get install ninja-build

**Comment by Jacky-gsq** [comment]
Thanks al lot! It works

> pip install ninja sudo apt-get install ninja-build
