### ISSUE TITLE
About LSSViewTransformerBEVStereo and LSSViewTransformerBEVDepth

### ISSUE THREAD

**Issue by Rayn-Wu** [Yzichen/FlashOCC#33]
Hi, thanks again for your great work!
I have a qustion about the **LSSViewTransformerBEVStereo**  . The code is:
```
class LSSViewTransformerBEVStereo(LSSViewTransformerBEVDepth):
    def __init__(self,  **kwargs):
        super(LSSViewTransformerBEVStereo, self).__init__(**kwargs)
        # (D, fH_stereo, fW_stereo, 3)  3:(u, v, d)
        self.cv_frustum = self.create_frustum(kwargs['grid_config']['depth'],
                                              kwargs['input_size'],
                                              downsample=4)
```
Whats the difference between **LSSViewTransformerBEVDepth** and **LSSViewTransformerBEVStereo**? Since ` self.cv_frustum` is not used.

**Comment by Yzichen** [comment]
https://github.com/Yzichen/FlashOCC/blob/0b424984e922a006b4e4b99832f853e6dca0b591/projects/mmdet3d_plugin/models/detectors/bevstereo4d.py#L84-L94

In fact, it is used, in order to calculate the stereo depth.

**Comment by Rayn-Wu** [comment]
thanks!
