### ISSUE TITLE
About the FPS

### ISSUE THREAD

**Issue by lzzzzzm** [Yzichen/FlashOCC#34]
when i test the FPS about the config of flashoccV2-4DLongterm-Depth(8f), it has a large gap between your show in the github

**Comment by Yzichen** [comment]
You should use benchmark_sequential.py to measure the fps.

**Comment by lzzzzzm** [comment]
okay, i will try

**Comment by BozhouZha** [comment]
> You should use benchmark_sequential.py to measure the fps.

@Yzichen   there, thank you for your great work! I wonder why the sequential flag is only set to True along with pred_prev during benchmark_sequential setting? I noticed that during normal inference (test time and training), these two are default to False which skips the extract_img_feat_sequential.
![image](https://github.com/user-attachments/assets/fd88bf29-2b2e-4483-ba49-595511178637)

Please correct me that if the extract_img_feat_sequential is the core part of "4D"?
