### ISSUE TITLE
the loss weight of loss_occ

### ISSUE THREAD

**Issue by yanyangchun** [Yzichen/FlashOCC#37]
https://github.com/Yzichen/FlashOCC/blob/5499075ba7b08c7661f9a2efa317a4fa1ce1ab00/projects/mmdet3d_plugin/models/dense_heads/bev_occ_head.py#L371
Please tell me, why its loss weight is 100, others is 1?

**Comment by Yzichen** [comment]
Just to balance the magnitude of the loss
