### ISSUE TITLE
[Bug] Incorrect Channel Order Flip during Image Loading

### ISSUE THREAD

**Issue by npurson** [Yzichen/FlashOCC#40]
There appears to be a bug in `projects/mmdet3d_plugin/datasets/pipelines/loading.py` at line 21. The `to_rgb = True` setting assumes that the images are initially in BGR format and then converts them to RGB. However, since the images are loaded using `Image.open()`, they are already in RGB format from the start.

**Comment by Yzichen** [comment]
You're right, thanks for the heads up .
