### ISSUE TITLE
Visualization of v1 and v2 model

### ISSUE THREAD

**Issue by Terencedu** [Yzichen/FlashOCC#42]
Hi, thank you for your great work! I have some questions of visualization of v1 and v2 model.

Config (v1 model): M3:FlashOCC-4D-Stereo (2f):
1. Why are there two vertical bars of blank space next to the ego car in many pictures?
![1](https://github.com/Yzichen/FlashOCC/assets/102672687/626e9025-4cc3-4b6f-bc9c-e4600634be95)
![2](https://github.com/Yzichen/FlashOCC/assets/102672687/24389950-95d0-40a4-a7a2-ecb67de68288)

Config (v2 model): FlashOCCV2-4DLongterm-Depth (16f):
1. Why is the ground plane basically blank？
2. This v2 model did not use camera mask for training. I think it can improve the prediction of invisible area like far sky compared to v1 model, but why does the v2 model predict both the sky and the ground poorly and which part improves in v2 model?
![3](https://github.com/Yzichen/FlashOCC/assets/102672687/b34f7bc9-0cc1-40b9-983a-7a62a4c55a01)

Hope to get your answer, thank you！

**Comment by Yzichen** [comment]
That's odd, I'll take some time to check it out when I'm not busy recently .

**Comment by Yzichen** [comment]
https://github.com/Yzichen/FlashOCC/blob/d1a41bc5fd99b290cb7f0d1642296c02cb7c58c3/tools/analysis_tools/vis_occ.py#L336-L340

The problem seems to be on voxel_show, which is now using the camera mask, so there's a lot of blank space in the invisible area. You can try it without it. 

when voxel_show = np.logical_and(pred_occ != FREE_LABEL, camera_mask):
![2024-05-28 20-56-15 的屏幕截图](https://github.com/Yzichen/FlashOCC/assets/54573533/1cc617f6-6c8b-493b-a0e8-a72bf7d04ea3)

when voxel_show = pred_occ != FREE_LABEL: 
![2024-05-28 20-56-52 的屏幕截图](https://github.com/Yzichen/FlashOCC/assets/54573533/d26662af-199e-4233-8bee-9e048201738c)

**Comment by shaozheng777** [comment]
Hello, I encountered the following issue while running test.py. Have you experienced this problem before? How should I resolve it?
Starting Evaluation...
  0%|                                                                                                                                                                          | 0/162 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "tools/test.py", line 290, in <module>
    main()
  File "tools/test.py", line 286, in main
    print(dataset.evaluate(outputs, **eval_kwargs))
  File "/home/wh/code/FlashOCC/projects/mmdet3d_plugin/datasets/nuscenes_dataset_occ.py", line 140, in evaluate
    self.occ_eval_metrics.add_batch(
  File "/home/wh/code/FlashOCC/projects/mmdet3d_plugin/core/evaluation/occ_metrics.py", line 172, in add_batch
    _, _hist = self.compute_mIoU(masked_semantics_pred, masked_semantics_gt, self.num_classes)
  File "/home/wh/code/FlashOCC/projects/mmdet3d_plugin/core/evaluation/occ_metrics.py", line 141, in compute_mIoU
    new_hist, correct, labeled = self.hist_info(n_classes, pred.flatten(), label.flatten())
  File "/home/wh/code/FlashOCC/projects/mmdet3d_plugin/core/evaluation/occ_metrics.py", line 118, in hist_info
    n_cl * gt[k].astype(int) + pred[k].astype(int), minlength=n_cl ** 2   
AttributeError: 'Tensor' object has no attribute 'astype'

**Comment by upupbo** [comment]
step 1. generate result
bash tools/dist_test.sh projects/configs/flashocc/flashocc-r50.py ckpts/flashocc-r50-256x704.pth 4 --eval map --eval-options show_dir=work_dirs/flashocc_r50/results

step 2. visualization
python tools/analysis_tools/vis_occ.py work_dirs/flashocc_r50/results/ --root_path ./data/nuscenes --save_path ./vis
An error occurs when running the second step：
vis: VisualizerWithKeyCallback with name Open3D
view_control: None
Traceback (most recent call last):
File "tools/analysis_tools/vis_occ.py", line 420, in
main()
File "tools/analysis_tools/vis_occ.py", line 359, in main
view_control.set_lookat(look_at)
AttributeError: 'NoneType' object has no attribute 'set_lookat'
