### ISSUE TITLE
visulization problem

### ISSUE THREAD

**Issue by uchiha-sasukee** [Yzichen/FlashOCC#43]
Hi, author.
Now I am using your visualization script tp visualize occupancy result, but one problem is that the view of the result is wrong, it looks like this:
![image](https://github.com/Yzichen/FlashOCC/assets/65847478/b1afeb99-f026-4041-bf50-084da6807177)
It's totally different from your post in this repo
Do you have any ideas about this problem?
By the way, my environment is 
open3d                        0.17.0
PyYAML                        5.3.1
torch                         1.10.0+cu111
torchaudio                    0.10.0+rocm4.1
torchpack                     0.3.1
torchvision                   0.11.0+cu111
mmcv-full                     1.5.3
mmdeploy                      0.9.0                
mmdet                         2.25.1               
mmdet3d                       1.0.0rc4             
mmsegmentation                0.25.0

**Comment by uchiha-sasukee** [comment]
![image](https://github.com/Yzichen/FlashOCC/assets/65847478/b3f4c165-c20c-4767-88cc-31edf48c0b16)
seem like it is under bev view, but I don't know how to transfer this view into the view in what your repo shows

**Comment by Yzichen** [comment]
You can try lowering the open3d version, like 0.13.0.

**Comment by uchiha-sasukee** [comment]
Thanks for for your reply, I solved this problem by using open3d 0.16.0, the result looks like this
![image](https://github.com/Yzichen/FlashOCC/assets/65847478/33148b34-6f02-487a-b262-6c22e2dfecd1)
but one more problem is that 
I feel that this image looks a bit rough. Do you know how to make it look more refined？
Thanks

**Comment by Yzichen** [comment]
Sorry, I have not explored this question either, you can try it and share it .
