### ISSUE TITLE
Some details about the Center Regression Head in Panoptic-FlashOcc

### ISSUE THREAD

**Issue by wcshen** [Yzichen/FlashOCC#48]
`Given that the BEV feature is a 2D flattened pillar representation rather than a 3D voxel representation, the regression for x and y represents the transitional ratio from the actual center to the discrete index, while the regression for z accounts for the estimation of the absolute height ratio.`

can you explain the generation of ground_truth and prediction_result of `(x,y,z)` in detail, best in examples

**Comment by drilistbox** [comment]
We kindly recommend to check the released code for detail examples.
