### ISSUE TITLE
About **Panoptic Occupancy Processing**

### ISSUE THREAD

**Issue by wcshen** [Yzichen/FlashOCC#49]
Heatmap and occ_semantic are not obtained from the same branch, the number of instance centers obtained by instance regression maybe different from the number of instances actually existing in occ_semantic, which may cause these problems:
1. There is not a distance threshold limit when looking for the nearest instance center point. If a very far center point is found, under-segmentation will occur, and the instance ID of multiple instances will be the same
2. If the heatmap head dosen't perform well, there will be many categories in the field of the same location which can't be filtered by maxpooling, then over-segmentation will occur, and multiple instance IDs will appear for the same instance

I don't know whether these issues will affect the final panoptic occupancy results...

**Comment by drilistbox** [comment]
Thanks for your suggestions. 
Heatmap and occ_semantic obtained from the same branch may alleviate the above 2 issues and promote the performance.
