### ISSUE TITLE
Is there long-term config?

### ISSUE THREAD

**Issue by SPA-junghokim** [Yzichen/FlashOCC#5]
Thank you for sharing your great research code.

Is there long-term config here or no?

thx

**Comment by drilistbox** [comment]
We are preparing to work on it.

**Comment by drilistbox** [comment]
we provide 2f, 8f and 16f setting.
https://github.com/Yzichen/FlashOCC/blob/master/projects/configs/panoptic-flashocc/panoptic-flashocc-r50-depth4d-pano.py
https://github.com/Yzichen/FlashOCC/blob/master/projects/configs/panoptic-flashocc/panoptic-flashocc-r50-depth4d-longterm8f.py
https://github.com/Yzichen/FlashOCC/blob/master/projects/configs/panoptic-flashocc/panoptic-flashocc-r50-depth4d-longterm16f-pano.py
