### ISSUE TITLE
Why Panoptic-FlashOcc can be faster so much than FlashOcc?

### ISSUE THREAD

**Issue by harrylin-hyl** [Yzichen/FlashOCC#51]
Great work! It appears that Panoptic-FlashOcc is built on FlashOcc with an additional centerness branch. Why is Panoptic-FlashOcc significantly faster than FlashOcc?

**Comment by drilistbox** [comment]
Thanks for your attention, but FlashOcc should be faster than Panoptic-FlashOcc. 
Where did you obtain the conclusion "Panoptic-FlashOcc significantly faster than FlashOcc" from?

**Comment by AIshenfeng** [comment]
![2024-07-29 17-32-44 的屏幕截图](https://github.com/user-attachments/assets/0ff4f148-99cb-4e0e-8ab6-b4430357508f)
In this table, Panoptic-FlashOcc is faster than FlashOcc.

**Comment by drilistbox** [comment]
Thanks for your attention. It is a mistake, we first test FlashOcc and Panoptic-FlashOcc on A6000 or 3090 (do not sure about this), and then only test Panoptic-FlashOcc on A100.
we will fix it later.

**Comment by cdb342** [comment]
In my own evaluation on A100, the FPS for FlashOcc is 29.5, for Pnoptic-FlashOcc-tiny (1f) it is 38.7, for Panostic-FlashOcc (1f) it is 29.5, and for Panostic-FlashOcc (8f) it is 25.4. I am puzzled by the fact that the results for FlashOcc are close to those listed in the table, whereas the results for Pnoptic-FlashOcc show a significant discrepancy. Could you provide some insights?

**Comment by drilistbox** [comment]
Thanks for your testing. 
And we test the FPS via A100(80G)(follow sparseocc) on autodl, the FPS on A100(80G) is faster than A100(40g).
What is the gpu memory of your A100, 40g or 80g?

**Comment by cdb342** [comment]
> Thanks for your testing. We will check it again. And we test the FPS via A100(80G)(follow sparseocc) on autodl, the FPS on A100(80G) is faster than A100(40g). What is the gpu memory of your A100, 40g or 80g?

Thanks for reaching out! I realized I made a mix-up in my previous message. I was actually using an RTX 4090 for those tests, not an A100. Additionally, when testing SparseOcc on the RTX 4090, I was able to replicate the results reported in the paper for the A100.
