### ISSUE TITLE
您好，请问为什么panoptic-flashocc对应配置的性能要低于flashocc?

### ISSUE THREAD

**Issue by winky4111** [Yzichen/FlashOCC#52]

**Comment by winky4111** [comment]
查看配置文件时发现，相应的配置文件下flashocc的性能要高于panoptic-flashocc,请问是什么原因导致的呢？

**Comment by winky4111** [comment]
在我的理解中，是新使用的3种策略造成的影响吗？

**Comment by drilistbox** [comment]
flashocc评测miou时，为了和bevdetocc,renderocc以及fbocc同比，是带camera_mask的。

而panoptic-flashocc评测miou时是不带camera_mask的。

评测miou时，如果不带camera_mask，miou指标会掉很多。

**Comment by Yzichen** [comment]
flashocc为了和bevdetocc,renderocc以及fbocc公平对比，在训练时使用了camera_mask，并且使用mIoU进行评估.
panoptic-flashocc在训练时没有使用camera_mask，虽然mIoU会有显著下降，但是Ray-IoU作为一个更合理的评价指标，是会上升的（具体可以参考SparseOCC）。

**Comment by winky4111** [comment]
感谢解答，请问其他两个策略对miou和ray-iou的影响又是怎样的呢？

**Comment by Yzichen** [comment]
深度监督和更佳的loss肯定对miou和ray-iou都有提升的

**Comment by winky4111** [comment]
好的，感谢感谢
