### ISSUE TITLE
run this project with my own dataset

### ISSUE THREAD

**Issue by Rogersljs** [Yzichen/FlashOCC#54]
Hello author, how can I run this project with my own dataset?

**Comment by Yzichen** [comment]
you need to make a nuscenes-like dataset and the occupancy annotations, the training process is the same.

**Comment by Rogersljs** [comment]
您好作者，请问我该如何使用自己的数据做测试？也需要构建像nuscenes的数据集吗？

**Comment by Rogersljs** [comment]
> you need to make a nuscenes-like dataset and the occupancy annotations, the training process is the same.

有制作nuscenes数据集的方法介绍吗？

**Comment by Yzichen** [comment]
Sorry, I'm not sure how to make a nuscenes dataset. However, you don't need to follow its format exactly, you just need to make sure you can make the same data_infos.

**Comment by Rogersljs** [comment]
> Sorry, I'm not sure how to make a nuscenes dataset. However, you don't need to follow its format exactly, you just need to make sure you can make the same data_infos.

ok thank you for you reply1

**Comment by Starboy-at-earth** [comment]
Dear Yzichen, Can I deploy FlashOCC onto a dog-robotics platform with just four cameras such as front, back, left, and right? Is ngineering a new dataset containing four raw images and Radar Semantics GT a must for the deployment?

**Comment by Starboy-at-earth** [comment]
@Yzichen
