### ISSUE TITLE
时序训练下，历史的bev feat如何对齐到当前帧

### ISSUE THREAD

**Issue by yanyangchun** [Yzichen/FlashOCC#56]
作者您好：
根据论文中的介绍，会对历史的bev feat做对齐，对齐到当前帧，
调试projects/configs/flashocc/flashocc-r50-4d-stereo.py，并进行阅读代码时，
发现得到前后帧的bev_feat_list后，就直接做了cat，没有去做对齐，
请教下，这块历史帧对齐到当前帧的代码是在哪儿实现的呢？

https://github.com/Yzichen/FlashOCC/blob/d64804d7bf4178b1a79284f50f53c1bbf79dd1aa/projects/mmdet3d_plugin/models/detectors/bevstereo4d.py#L220

**Comment by Yzichen** [comment]
https://github.com/Yzichen/FlashOCC/blob/d64804d7bf4178b1a79284f50f53c1bbf79dd1aa/projects/mmdet3d_plugin/models/detectors/bevdet4d.py#L241-L249

If _**align_after_view_transfromation=True**_ is not specified, the temporal alignment is done in the view transfromer. To do this, the transform matrix **_sensor2keyegos_** from the camera to the current ego system is computed for each frame, which can be seen in the above code.

**Comment by yanyangchun** [comment]
> https://github.com/Yzichen/FlashOCC/blob/d64804d7bf4178b1a79284f50f53c1bbf79dd1aa/projects/mmdet3d_plugin/models/detectors/bevdet4d.py#L241-L249
> 
> If _**align_after_view_transfromation=True**_ is not specified, the temporal alignment is done in the view transfromer. To do this, the transform matrix **_sensor2keyegos_** from the camera to the current ego system is computed for each frame, which can be seen in the above code.

感谢解答，仔细看了代码后，发现是将第一帧（当前帧）的第一个view的ego2global作为keyego2global，然后历史帧的所有view投影到keyego上，相当于同时解决了历史帧对齐，多view对齐的工作。

**Comment by xuanzhangyang** [comment]
> > https://github.com/Yzichen/FlashOCC/blob/d64804d7bf4178b1a79284f50f53c1bbf79dd1aa/projects/mmdet3d_plugin/models/detectors/bevdet4d.py#L241-L249
> > 
> > If _**align_after_view_transfromation=True**_ is not specified, the temporal alignment is done in the view transfromer. To do this, the transform matrix **_sensor2keyegos_** from the camera to the current ego system is computed for each frame, which can be seen in the above code.
> 
> 感谢解答，仔细看了代码后，发现是将第一帧（当前帧）的第一个view的ego2global作为keyego2global，然后历史帧的所有view投影到keyego上，相当于同时解决了历史帧对齐，多view对齐的工作。

@yanyangchun 你好，我对时序对齐这块一直不太清楚原理，你能帮详细解释一下吗？
