### ISSUE TITLE
flash-occ inference error

### ISSUE THREAD

**Issue by Monssica** [Yzichen/FlashOCC#58]
when i test flash-occ  ,I encountered the following problem:
![error](https://github.com/user-attachments/assets/be4f4089-ceba-489d-9e53-ca6deb4a0a7a)
and with the inference time, the gpu memory grows all the time，is that right?

**Comment by drilistbox** [comment]
what is your test cmd

**Comment by Monssica** [comment]
python tools/test.py projects/configs/flashocc/flash-occ-r50.py ckpts/flashocc-r50-256×704.pth --eval mAP --gpu-id 1

**Comment by shaozheng777** [comment]
I have encountered the same problem. How can I solve it?

**Comment by drilistbox** [comment]
Thanks for your attention, the bug is fixed, please pull the code and test again.

**Comment by drilistbox** [comment]
> > when i test flash-occ ,I encountered the following problem: ![error](https://private-user-images.githubusercontent.com/51433003/358535625-be4f4089-ceba-489d-9e53-ca6deb4a0a7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxODIwMDksIm5iZiI6MTcyNzE4MTcwOSwicGF0aCI6Ii81MTQzMzAwMy8zNTg1MzU2MjUtYmU0ZjQwODktY2ViYS00ODlkLTllNTMtY2E2ZGViNGEwYTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDEyNDE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmY2U5ZDhkMGJkZmY0ZjNlMGU2YTZmOGZlOTdiNThjNmRhMTk4YjU2MTVjMmNhZmRjZGUzMDJlOTBjN2E0NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hHkxhyOWCIga6-0P6cLyJrB_AIa36-lR8dIjTU4MurQ) and with the inference time, the gpu memory grows all the time，is that right?
> 
> Hello, how did you solve your problem?

we update the code last week, please pull the code and test again
