### ISSUE TITLE
Why BEVDepthOCC gets worse results than BEVDetOCC ?

### ISSUE THREAD

**Issue by JYounngS** [Yzichen/FlashOCC#59]
I changed the model type and img_view_transformer type in the config file, then I can only get mIoU of 27.84. Instead, if I always set the loss_depth to 0 while keeping the same config file, I can obtain mIoU of 31.9.

**Comment by JYounngS** [comment]
Has anyone tried to use the BEVDepth as your baseline?

**Comment by Gang-Chen-China** [comment]
Have you tried it again? I am curious about it.

**Comment by zswzswzsw233** [comment]
> I changed the model type and img_view_transformer type in the config file, then I can only get mIoU of 27.84. Instead, if I always set the loss_depth to 0 while keeping the same config file, I can obtain mIoU of 31.9.

应该是预训练权重的问题，没有提供bevdet-r50-depth-cbgs.pth这个权重
