### ISSUE TITLE
Test server result

### ISSUE THREAD

**Issue by vehxianfish** [Yzichen/FlashOCC#6]
Hi, @Yzichen. Thanks for your wonderful work. Is the result uploaded to the official server in [leaderboard](https://eval.ai/web/challenges/challenge-page/2045/leaderboard/4838) for evaluation?
Looking forward to your reply.
Best wishes!

**Comment by Yzichen** [comment]
No, we only evaluated it on the validation set.

**Comment by vehxianfish** [comment]
> No, we only evaluated it on the validation set.

Thanks.
