### ISSUE TITLE
加入激光雷达信息进行推理

### ISSUE THREAD

**Issue by Rogersljs** [Yzichen/FlashOCC#61]
作者您好，我想加入激光雷达信息在推理阶段，请问我该如何修改？

**Comment by drilistbox** [comment]
感觉可以参考bevfusion系列论文

**Comment by Rogersljs** [comment]
> 感觉可以参考bevfusion系列论文

好的 我试一试 你们有使用激光雷达加入推理的尝试吗？

**Comment by drilistbox** [comment]
没，但是激光雷达的融入应该是能提升效果的

**Comment by drilistbox** [comment]
这个论文貌似做了点云和视觉的融合，https://arxiv.org/pdf/2406.07042

**Comment by Gu718-git** [comment]
> > 感觉可以参考bevfusion系列论文
> 
> 好的 我试一试 你们有使用激光雷达加入推理的尝试吗？

请问您尝试过了吗？
