### ISSUE TITLE
The backbone of M3:FlashOCC-4D-Stereo (2f) should be Swin-B

### ISSUE THREAD

**Issue by AlphaPlusTT** [Yzichen/FlashOCC#68]
Swin-T:  C = 96, layer numbers = {2, 2, 6, 2}
 Swin-B: C = 128, layer numbers ={2, 2, 18, 2}

**Comment by Yzichen** [comment]
Yes, our model name is incorrect, both we and BEVDet use Swin-B. Thanks.
