### ISSUE TITLE
Regarding acceleration in evaluating FPS

### ISSUE THREAD

**Issue by cdb342** [Yzichen/FlashOCC#71]
![img_v3_02ff_de20efd9-fbb1-4c4e-ba7f-20981a2f47cg](https://github.com/user-attachments/assets/5980d183-fee0-4619-a6cb-2a263cd1b6e3)
It appears that acceleration is used when evaluating FPS, which assumes fixed camera extrinsics and intrinsics for each sample. However, in the NuScenes dataset, camera parameters change even between frames. I suspect the appropriateness of making this assumption when measuring FPS, especially since other works don't seem to make this assumption.

**Comment by Yzichen** [comment]
In fact, we make this assumption following bevdet. Moreover, we believe that in practice, the extrinsics and intrinsics are fixed, so this assumption is reasonable, despite the performance degradation for nuscenes.

**Comment by cdb342** [comment]
> In fact, we make this assumption following bevdet. Moreover, we believe that in practice, the extrinsics and intrinsics are fixed, so this assumption is reasonable, despite the performance degradation for nuscenes.

Thanks for your response. Do you know why the camera parameters change between frames in nuscenes. Are they calibrated frame by frame?

**Comment by BozhouZha** [comment]
> > In fact, we make this assumption following bevdet. Moreover, we believe that in practice, the extrinsics and intrinsics are fixed, so this assumption is reasonable, despite the performance degradation for nuscenes.
> 
> Thanks for your response. Do you know why the camera parameters change between frames in nuscenes. Are they calibrated frame by frame?

I don't think they calibrated frame by frame but clip by clip. The dataset was collectively from both Singapore and Boston, so the extrinsic may vary as they shipped the vehicle. It might be more systematic way to attach intrins&extrins to each frame instead of adding extra tag to tell us when they recalibrated the cameras.

**Comment by cdb342** [comment]
> > > In fact, we make this assumption following bevdet. Moreover, we believe that in practice, the extrinsics and intrinsics are fixed, so this assumption is reasonable, despite the performance degradation for nuscenes.
> > 
> > 
> > Thanks for your response. Do you know why the camera parameters change between frames in nuscenes. Are they calibrated frame by frame?
> 
> I don't think they calibrated it frame by frame but clip by clip. The dataset was recorded collectively from both Singapore and Boston, so the extrinsic may vary as they shipped the vehicle or they changed vehicle. It might be a more systematic way to attach intrins&extrins to each frame instead of adding extra tag to tell us when they recalibrated the cameras.

Apologies for any confusion, and thank you for your patience. I have carefully checked, and it turns out that the camera parameters in the NuScenes dataset are indeed consistent across all scenes.
