### ISSUE TITLE
No module named 'tools.data_converter'

### ISSUE THREAD

**Issue by zydczqcnydx** [Yzichen/FlashOCC#74]
(FlashOcc) ~/learn_ws/src/FlashOCC(*master)$ python tools/create_data_bevdet.py
Traceback (most recent call last):
  File "tools/create_data_bevdet.py", line 9, in <module>
    from tools.data_converter import nuscenes_converter as nuscenes_converter
ModuleNotFoundError: No module named 'tools.data_converter'

**Comment by xuanzhangyang** [comment]
cd Path_to_FlashOcc/FlashOcc/mmdetection3d
git checkout v1.0.0rc4
pip install -v -e .

**Comment by zydczqcnydx** [comment]
export PYTHONPATH=./

the shell can resolve my bug
