### ISSUE TITLE
ModuleNotFoundError: No module named 'projects'

### ISSUE THREAD

**Issue by zydczqcnydx** [Yzichen/FlashOCC#76]
python tools/train.py projects/configs/flashocc/flashocc-r50.py

how to solve？

**Comment by zydczqcnydx** [comment]
python tools/train.py ./projects/configs/flashocc/flashocc-r50.py
/home/zhenqiang.cao/miniconda3/envs/FlashOcc/lib/python3.8/site-packages/mmdet/utils/setup_env.py:38: UserWarning: Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
/home/zhenqiang.cao/miniconda3/envs/FlashOcc/lib/python3.8/site-packages/mmdet/utils/setup_env.py:48: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
projects.mmdet3d_plugin
Traceback (most recent call last):
  File "tools/train.py", line 286, in <module>
    main()
  File "tools/train.py", line 139, in main
    plg_lib = importlib.import_module(_module_path)
  File "/home/zhenqiang.cao/miniconda3/envs/FlashOcc/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in

**Comment by Yzichen** [comment]
Have you performed the following steps?
```
cd Path_to_FlashOcc/FlashOcc/projects
pip install -v -e . 
```

**Comment by Yzichen** [comment]
You can check the environment variable, if it contains the path of the flashocc project.

```
import sys
print(sys.path)
sys.path.insert(0,  your_flashocc_path)
```

**Comment by songhc8** [comment]
I have the same problem. 
my IDE is vscode, and i install all packages following your instructions. but when I am trying to train the model. I get the same error messages.  here is my vscode configs:
`
"configurations": [
        {
            "name": "train onegpu",
            "type": "debugpy",
            "request": "launch",
            "program": "${workspaceFolder}/tools/train.py",
            "args": ["${workspaceFolder}/projects/configs/panoptic-flashocc/panoptic-flashocc-r50-depth-pano.py"],
            "cwd": "${workspaceFolder}/projects",
            "console": "integratedTerminal"
        }
    ]
`
 Even I do not use vscode and run the command in terminal . still get same error messages.

**Comment by songhc8** [comment]
after installing all packages following the auther's instructions. activate your virtual environment, and update your PYTHONPATH. 
`export PYTHONPATH=${PYTHONPATH}:/path/to/FlashOCC`. The bug will be fixed.
