### ISSUE TITLE
downsample=16和downsample=8的精度差多少，有做过实验吗

### ISSUE THREAD

**Issue by rubbish001** [Yzichen/FlashOCC#78]
downsample=16和downsample=8的精度差多少，有做过实验吗

**Comment by rubbish001** [comment]
我在看了一下配置，你用是16，我测试过16在4090上，用1056*386的分辨率，2帧耗时230ms，但是8的时候耗时500多ms

**Comment by Yzichen** [comment]
https://github.com/Yzichen/FlashOCC/issues/68#issuecomment-2362542402

我们并非偷偷加深, 只是模型名字写错了,忘记修改了.  我们swin骨干和BEVDet是对应的.

**Comment by WenxuanLi-whu** [comment]
哦哦，我发现耗时主要卡在LSS上，downsample =8时，有900w个点需要转换，所以特别慢，看样子downsapme=16是正解
