### ISSUE TITLE
Visual testing reveals problems

### ISSUE THREAD

**Issue by upupbo** [Yzichen/FlashOCC#84]
# step 1. generate result 
bash tools/dist_test.sh projects/configs/flashocc/flashocc-r50.py ckpts/flashocc-r50-256x704.pth 4 --eval map --eval-options show_dir=work_dirs/flashocc_r50/results
# step 2. visualization
python tools/analysis_tools/vis_occ.py work_dirs/flashocc_r50/results/ --root_path ./data/nuscenes --save_path ./vis
An error occurs when running the second step：
vis: VisualizerWithKeyCallback with name Open3D
view_control: None
Traceback (most recent call last):
  File "tools/analysis_tools/vis_occ.py", line 420, in <module>
    main()
  File "tools/analysis_tools/vis_occ.py", line 359, in main
    view_control.set_lookat(look_at)
AttributeError: 'NoneType' object has no attribute 'set_lookat'

**Comment by Gu718-git** [comment]
I'm having the same issue, has it been solved?

**Comment by Yzichen** [comment]
If your server is not connected to a monitor, you can download the data locally.

**Comment by lnSong** [comment]
I have encountered the same problem, have you solved it?
