### ISSUE TITLE
Environment Error - mmcv version mismatch. 

### ISSUE THREAD

**Issue by amirlivne** [Yzichen/FlashOCC#86]
when trying to tun `test.py`, on line 14:
`import mmdet`

I get the following error:
`AssertionError: MMCV==1.5.3 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.2.0.`

My installed mmdet version is `2.25.1` as mentioned in the install.md page.

Does anyone else encountered this issue?

**Comment by Yzichen** [comment]
Can I see your pip list?

**Comment by amirlivne** [comment]
I reinstalled all of the packages and it fixed the issue. 
Thank you for the quick reply!
