### ISSUE TITLE
a question about the semantic categories in the configuration file

### ISSUE THREAD

**Issue by Kongbaikb** [Yzichen/FlashOCC#9]
Thank you very much for your outstanding work. I would like to ask why there are only 10 semantic categories in the configuration file, which does not meet the 17 categories in the paper.

**Comment by Yzichen** [comment]
The categories in the config are the categories of the object detection, the occupation categories can be seen here:
https://github.com/Yzichen/FlashOCC/blob/0599dbab1db8df39f7e644dd2f67e996d0232eef/projects/mmdet3d_plugin/core/evaluation/occ_metrics.py#L59-L62
